dist: bionic
sudo: false
language: php

php:
  - 7.3
  - 7.4

env:
  - DB=mariadb104
  - DB=sqlite3
  - DB=mysql56
  - DB=mysql57
  - DB=pgsql94
  - DB=pgsql100

before_install:
  - |
    if [[ $COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update

install:
  - rm composer.lock
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress --optimize-autoloader

script:
  - |
    if [[ "$DB" == "mysql56" || "$DB" == "mysql57" ||  "$DB" == "mariadb104" ]]; then
      mysql -e "CREATE SCHEMA doctrine_tests; GRANT ALL PRIVILEGES ON doctrine_tests.* to travis@'%'";
    fi
  - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml
  # temporarily disabled
  #- ENABLE_SECOND_LEVEL_CACHE=1 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --exclude-group performance,non-cacheable,locking_functional

jobs:
  include:
    - stage: Test
      env: DB=mariadb104
      addons:
        mariadb: '10.4'

    - stage: Test
      env: DB=mysql56
      sudo: required
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6

    - stage: Test
      env: DB=pgsql94
      addons:
        postgresql: '9.4'

    - stage: Test
      env: DB=sqlite3 DEPENDENCIES=low
      install:
        - travis_retry composer update --no-interaction --prefer-dist --no-suggest --prefer-lowest --no-progress --optimize-autoloader

    - stage: Test
      if: type = cron
      env: DB=sqlite3 DEV_DEPENDENCIES
      install:
        - rm composer.lock
        - composer config minimum-stability dev
        - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress --optimize-autoloader

    - stage: Test
      env: DB=sqlite COVERAGE=1
      before_script:
        - phpenv config-add xdebug.ini
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --coverage-clover ./build/logs/clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: Code Quality
      env: DB=none BENCHMARK
      before_script:
        - wget https://phpbench.github.io/phpbench/phpbench.phar https://phpbench.github.io/phpbench/phpbench.phar.pubkey
      script: php phpbench.phar run --bootstrap=tests/Doctrine/Tests/TestInit.php -l dots --report=default

  allow_failures:
    # temporarily disabled
    - env: DB=mariadb104
    - env: DB=mysql56
    - env: DB=mysql57
    - env: DB=pgsql94
    - env: DB=pgsql100

cache:
  directories:
    - $HOME/.composer/cache
