dist: bionic
sudo: false
language: php

php:
  - 7.3
  - 7.4

env:
  - DB=mariadb
  - DB=sqlite
  - DB=mysql
  - DB=pgsql

before_install:
  - |
    if [[ "$COVERAGE" != "1" ]]; then
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update

install:
  - rm composer.lock
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress --optimize-autoloader

script:
  - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml
  # temporarily disabled
  #- ENABLE_SECOND_LEVEL_CACHE=1 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --exclude-group performance,non-cacheable,locking_functional

jobs:
  include:

    - stage: Test
      env: DB=pgsql
      services:
        - postgresql

    - stage: Test
      env: DB=mysql
      services:
        - mysql

    - stage: Test
      env: DB=mariadb
      services:
        - mariadb
      addons:
        mariadb: '10.4'

    - stage: Test
      env: DB=sqlite DEPENDENCIES=low
      install:
        - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress --prefer-lowest

    - stage: Test
      if: type = cron
      env: DB=sqlite DEV_DEPENDENCIES
      install:
        - rm composer.lock
        - composer config minimum-stability dev
        - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress

    - stage: Test
      env: DB=sqlite COVERAGE=1
      before_script:
        - phpenv config-add xdebug.ini
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --coverage-clover ./build/logs/clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: Code Quality
      env: DB=none BENCHMARK
      before_script:
        - wget https://phpbench.github.io/phpbench/phpbench.phar https://phpbench.github.io/phpbench/phpbench.phar.pubkey
      script: php phpbench.phar run --bootstrap=tests/Doctrine/Tests/TestInit.php -l dots --report=default

  allow_failures:
    # temporarily disabled
    - env: DB=mariadb
    - env: DB=mysql
    - env: DB=pgsql

cache:
  directories:
    - $HOME/.composer/cache
