sudo: false
language: php

# Required for HHVM builds
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

services:
  - mysql

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' && $DB = 'sqlite' ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi
  - if [[ $TRAVIS_PHP_VERSION -lt '7.0' && $TRAVIS_PHP_VERSION != 'hhv*' ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' ]]; then echo hhvm.php7.scalar_types=0 >> /etc/hhvm/php.ini; fi
  - composer self-update
  - composer install --prefer-source

script:
  - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml $PHPUNIT_FLAGS --stop-on-error
  - ENABLE_SECOND_LEVEL_CACHE=1 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --exclude-group performance,non-cacheable,locking_functional --stop-on-error

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' && $DB = 'sqlite' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.0' && $DB = 'sqlite' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: hhvm
      sudo: true
      addons:
        mariadb: 10.1
      env: DB=mariadb
    - php: hhvm
      sudo: true
      env: DB=mysql
    - php: hhvm
      sudo: true
      services:
        - postgresql
      env: DB=pgsql
    - php: hhvm
      sudo: true
      env: DB=sqlite

  allow_failures:
    - php: nightly
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
