on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring
        tools: composer, cs2pr, phpcs

    - name: composer install
      run: composer install --no-progress

    - name: phpcs
      run: php vendor/bin/phpcs -q --report=checkstyle --no-colors | cs2pr
